added models
SickleShaped/Corbae pull request #1
Opened 2023-02-19 20:51 UTC by SickleShaped

Db created

2023-02-20 06:21 UTC, EreminNikolai requested changes

2023-02-20 06:21 UTC, EreminNikolai commented on .dockerignore
> +**/.classpath
папку .vs и все остальные, которые не требуется для сборки проекта должны быть убраны из коммита и добавлены в .gitignore. Если возникают сложности какие  еще папку нужно убрать, то в интете есть готовые файлы, только выбрать тип проекта .net core

2023-02-20 06:21 UTC, EreminNikolai commented on Corbae/ApiDbContext.cs
> +            optionsBuilder.UseNpgsql("Host=localhost;Port=5432;Database=corbaedb;Username=postgres;Password=9p8o7i6u");
Подключение к БД нужно вынести в AppConfig.json

2023-02-20 06:21 UTC, EreminNikolai commented on Corbae/Migrations/20230209104413_Initial.cs
> +            migrationBuilder.CreateTable(
Подумай, что  будет с твоими связанными данными, если в какой-то из моделей необходимо удалить запись. Есть два варианта: 
1) Запись удаляется физически, а значит все связанные с ней записи тоже должны удаляться, но тогда в этом случае нужно добавить флаг каскадного удаления
2) Удаление фиктивное, тогда для всех моделей нужно добавить поле isdeleted и проставлять флаг, а так же во всех select не забывать об этом поле. В этом варианте лучше всего подойдет паттерн Repository

2023-02-20 06:21 UTC, EreminNikolai commented on Corbae/Models/Cart.cs
> +        public string UserId { get; set; }
Все открытые свойства, методы, делегаты, события и т.п. должны быть описаны <summary>

2023-02-24 10:08 UTC, SickleShaped commented on .dockerignore
> +**/.classpath
1378fa0914052ae5dd246164f657eefcaeb8990d

2023-02-27 16:10 UTC, SickleShaped commented on Corbae/Models/Cart.cs
> +        public string UserId { get; set; }
031fc0921e8372619a0bed666bc91cad7427ef27

2023-02-28 18:25 UTC, closed without merging